config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients
  resources :ingredients
  resources :allergies 
  resources :recipes
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allergy.rb
class Allergy < ApplicationRecord
    belongs_to :user
    belongs_to :ingredient 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :allergies
    has_many :recipes , through: :recipe_ingredients 
    
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :ingredients , through: :recipe_ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    belongs_to :recipe 
    belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    has_many :allergies
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
    class RecipesController < ApplicationController
    
        before_action :find_recipe, only: [:show , :edit ,:update , :destroy]
    
                def index
                    @recipes = Recipe.all
                end 

                def show 
               
                end 

                def new
                    @recipe = Recipe.new
                end 

                def create
                    @create = Recipe.create(recipe_strong_params)
                    redirect_to recipes_path 
                end 

                def edit
        
                end 

                def update
                    @recipe.update(recipe_strong_params)
                    redirect_to recipe_path(@recipe)
                end 

                def destroy
                    @recipe.delete
                    redirect_to recipes_path
                end 



        private

        def find_recipe
            @recipe = Recipe.find(params[:id])
        end 

        def recipe_strong_params
            params.require(:recipe).permit(:name,:user_id)
        end 

    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allergens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_recipe_form.html.erb
<%= form_for @recipe do |f|%>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :user_id %>
<%= f.collection_select :user_id , User.all , :id , :name %>
<%= f.submit %>
<% end %>    

app/views/recipes/edit.html.erb
<h3> Edit Recipe Here </h3> 

<%= form_for @recipe do |f|%>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :user_id %>
<%= f.collection_select :user_id , User.all , :id , :name %>
<%= f.submit %>
<% end %>    

app/views/recipes/index.html.erb
<h1> Welcome to My Recipe App </h1> 


<% @recipes.each do |recep| %>
<%= link_to recep.name , recipe_path(recep) %><br>
<% end %>
<br><br>

<%= link_to "Create New Recipe", new_recipe_path(@recipe) %>

app/views/recipes/new.html.erb
<h3> Create a New Recipe </h3>




<%= render partial: "recipe_form"  %>
 

app/views/recipes/show.html.erb
<h1> See More Details for <%= @recipe.name %> <h1>

<h3><%= link_to "Home page", recipes_path  %></h3> 

<%= link_to "Delete Recipe" , recipe_path(@recipe),:method => :delete , data: {:confirm => "Are You Sure? "} %>